In [1]:
import numpy as np
import pandas as pd
import sklearn.model_selection
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from keras import regularizers

In [2]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar100.load_data(
    label_mode='fine'
)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

y_train = tf.keras.utils.to_categorical(y_train, 100)
y_test = tf.keras.utils.to_categorical(y_test, 100)

In [3]:
weight_decay = 0.0005
model = tf.keras.Sequential([
    layers.Conv2D(64, (3,3), padding = 'same', input_shape = (32,32,3),kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    layers.Conv2D(64, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.MaxPooling2D((2,2)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(128, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(128, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.MaxPooling2D((2,2)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(256, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(256, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(256, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.MaxPooling2D((2,2)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(512, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(512, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Conv2D(512, (3,3), padding = 'same', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.MaxPooling2D((2,2)),
    layers.Activation('relu'),
    layers.BatchNormalization(),
    
    layers.Flatten(),
    layers.Dense(512, activation = 'relu', kernel_regularizer=regularizers.l2(weight_decay)),
    layers.BatchNormalization(),
    
    layers.Dense(100, activation = 'softmax',kernel_regularizer=regularizers.l2(weight_decay))
    
])

In [4]:
model.compile(optimizer ='adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy']
             )

In [9]:
model.fit(X_train[:100], y_train[: 100], epochs=3, )

Epoch 1/3
4/4 [==============================] - 7s 1s/step - loss: 6.9886 - accuracy: 0.0100
Epoch 2/3
4/4 [==============================] - 5s 1s/step - loss: 5.2082 - accuracy: 0.2600
Epoch 3/3
4/4 [==============================] - 5s 1s/step - loss: 4.1197 - accuracy: 0.4700


In [10]:
model.weights

[<tf.Variable 'conv2d_20/kernel:0' shape=(3, 3, 3, 64) dtype=float32, numpy=
 array([[[[-0.01168424,  0.08460853,  0.05399982, ...,  0.08352603,
           -0.03168229, -0.08710948],
          [ 0.09500381, -0.06777482,  0.08164835, ...,  0.03297694,
           -0.00288345, -0.05430127],
          [ 0.06294011, -0.03805081, -0.0815499 , ..., -0.05070249,
           -0.07585169, -0.08928984]],
 
         [[ 0.04723337, -0.03381253,  0.02537024, ...,  0.07947073,
           -0.05575078,  0.00103792],
          [-0.02069421,  0.04428756,  0.00129962, ..., -0.00915706,
            0.05440336, -0.09439795],
          [-0.02175661,  0.0412993 ,  0.00399427, ..., -0.01964848,
            0.01213288, -0.06076422]],
 
         [[ 0.08181982, -0.02098299,  0.0180179 , ...,  0.065054  ,
            0.06663919, -0.0181876 ],
          [ 0.06360121,  0.04525617,  0.0859867 , ..., -0.0615443 ,
           -0.01149155,  0.05335068],
          [ 0.03552669,  0.03496801, -0.01604914, ...,  0.00663885,
 

In [12]:
model.save_weights('cifar100vgg1.h5')

In [5]:
model.load_weights('cifar100vgg1.h5')

In [6]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 64) dtype=float32, numpy=
 array([[[[-0.01168424,  0.08460853,  0.05399982, ...,  0.08352603,
           -0.03168229, -0.08710948],
          [ 0.09500381, -0.06777482,  0.08164835, ...,  0.03297694,
           -0.00288345, -0.05430127],
          [ 0.06294011, -0.03805081, -0.0815499 , ..., -0.05070249,
           -0.07585169, -0.08928984]],
 
         [[ 0.04723337, -0.03381253,  0.02537024, ...,  0.07947073,
           -0.05575078,  0.00103792],
          [-0.02069421,  0.04428756,  0.00129962, ..., -0.00915706,
            0.05440336, -0.09439795],
          [-0.02175661,  0.0412993 ,  0.00399427, ..., -0.01964848,
            0.01213288, -0.06076422]],
 
         [[ 0.08181982, -0.02098299,  0.0180179 , ...,  0.065054  ,
            0.06663919, -0.0181876 ],
          [ 0.06360121,  0.04525617,  0.0859867 , ..., -0.0615443 ,
           -0.01149155,  0.05335068],
          [ 0.03552669,  0.03496801, -0.01604914, ...,  0.00663885,
    

In [14]:
predicted_x = model.predict(X_test[:100])
residuals = (np.argmax(predicted_x,1)==np.argmax(y_test[:100],1))
acc = sum(residuals)/len(residuals)

acc5 = (np.argmax(y_test,1).reshape((y_test.shape[0], 1)) == np.argsort(predicted_x, axis = 1)[:,-5:]).sum(axis=1).sum()/len(residuals)
print("the validation 0/1 accuracy top1 is: ",acc)
print("the validation 0/1 accuracy top5 is: ",acc5)

<ipython-input-14-8ace9e7252d5>:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  acc5 = (np.argmax(y_test,1).reshape((y_test.shape[0], 1)) == np.argsort(predicted_x, axis = 1)[:,-5:]).sum(axis=1).sum()/len(residuals)


AttributeError: 'bool' object has no attribute 'sum'

In [54]:
from __future__ import print_function
import keras
from keras.datasets import cifar100
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from keras import optimizers
import numpy as np
from keras.layers.core import Lambda
from keras import backend as K
from keras import regularizers
from tensorflow import keras


In [68]:
model = Sequential()
weight_decay = 0.0005

model.add(Conv2D(64, (3, 3), padding='same',
             input_shape=(32, 32, 3),kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.3))

model.add(Conv2D(64, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(128, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(256, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(256, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())
#model.add(Dropout(0.4))

model.add(Conv2D(512, (3, 3), padding='same',kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(512,kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(BatchNormalization())

#model.add(Dropout(0.5))
model.add(Dense(100))
model.add(Activation('softmax'))

In [69]:
batch_size = 128
maxepoches = 109
learning_rate = 0.1
lr_decay = 1e-6
lr_drop = 20

# sgd = tf.keras.optimizers.SGD(lr=learning_rate, decay=lr_decay, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [70]:
model.fit(X_train[:100], y_train[:100], epochs=10)

Epoch 1/10
4/4 [==============================] - 21s 2s/step - loss: 7.7703 - accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 8s 2s/step - loss: 6.6964 - accuracy: 0.0554
Epoch 3/10
4/4 [==============================] - 6s 1s/step - loss: 6.1705 - accuracy: 0.1141
Epoch 4/10
4/4 [==============================] - 8s 2s/step - loss: 5.9108 - accuracy: 0.1478
Epoch 5/10
4/4 [==============================] - 7s 2s/step - loss: 5.8172 - accuracy: 0.1916
Epoch 6/10
4/4 [==============================] - 8s 2s/step - loss: 5.7070 - accuracy: 0.1574
Epoch 7/10
4/4 [==============================] - 6s 1s/step - loss: 5.5261 - accuracy: 0.2276
Epoch 8/10
4/4 [==============================] - 8s 2s/step - loss: 5.5373 - accuracy: 0.1878
Epoch 9/10
4/4 [==============================] - 7s 2s/step - loss: 5.3044 - accuracy: 0.2062
Epoch 10/10
4/4 [==============================] - 7s 2s/step - loss: 5.3233 - accuracy: 0.3169


In [81]:
np.argmax(model.predict(X_train[200:400]), 1)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99], dtype=int64)

In [74]:
np.argmax(y_test[:100], 1)

array([49, 33, 72, 51, 71, 92, 15, 14, 23,  0, 71, 75, 81, 69, 40, 43, 92,
       97, 70, 53, 70, 49, 75, 29, 21, 16, 39,  8,  8, 70, 20, 61, 41, 93,
       56, 73, 58, 11, 25, 37, 63, 24, 49, 73, 56, 22, 41, 58, 75, 17,  4,
        6,  9, 57,  2, 32, 71, 52, 42, 69, 77, 27, 15, 65,  7, 35, 43, 82,
       63, 92, 66, 90, 67, 91, 32, 32, 82, 10, 77, 22, 71, 78, 54,  6, 29,
       89, 78, 33, 11, 67, 22, 18, 27, 21, 13, 21, 50, 75, 37, 35],
      dtype=int64)

In [78]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_39 (Conv2D)           (None, 32, 32, 64)        1792      
_________________________________________________________________
activation_44 (Activation)   (None, 32, 32, 64)        0         
_________________________________________________________________
batch_normalization_14 (Batc (None, 32, 32, 64)        256       
_________________________________________________________________
conv2d_40 (Conv2D)           (None, 32, 32, 64)        36928     
_________________________________________________________________
activation_45 (Activation)   (None, 32, 32, 64)        0         
_________________________________________________________________
batch_normalization_15 (Batc (None, 32, 32, 64)        256       
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 16, 16, 64)       